baseurl = ""
relativeurls = true
languageCode = "en-us"
title = "NYC Mesh Docs"
pluralizeListTitles = false
hrefTargetBlank = true
enableGitInfo = true

# Markdown config
[blackfriday]
fractions = false
hrefTargetBlank = true
