site_name: Tucson Mesh Documentation 
theme:
  name: material
  features:
    - content.action.edit
  palette:
    primary: black
  logo: assets/logo.jpg
repo_url: https://github.com/tucsonmesh/tucsonmesh-docs
repo_name: tucsonmesh/tucsonmesh-docs 
edit_uri: edit/main/docs
nav:
  - Home: index.md
  - Guides:
    - guides/installation/index.md
    - guides/site-survey/index.md
    - guides/configuring-routers/index.md
    - guides/ladder-safety.md
    - Updating this documentation:
      - guides/updating-docs/index.md
      - guides/updating-docs/editing-docs.md
  - Hardware:
    - hardware/omnitik.md
    - hardware/liteap.md
    - hardware/litebeam.md
    - hardware/sxtsq.md
  - Networking:
    - Supernodes:
      - networking/supernodes/index.md
      - networking/supernodes/bicas.md
      - networking/supernodes/tucson-house.md
    - networking/networking101.md
