site_name: Tucson Mesh Documentation 
theme:
  name: material
  features:
    - content.action.edit
    - navigation.footer
  palette:
    primary: black
  logo: assets/logo.jpg
repo_url: https://github.com/tucsonmesh/tucsonmesh-docs
repo_name: tucsonmesh/tucsonmesh-docs 
edit_uri: edit/main/docs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Guides:
    - guides/about-your-node/index.md
    - guides/site-survey/index.md
    - Router Configuration:
      - guides/configuring-routers/index.md
      - guides/configuring-routers/litebeam.md
      - guides/configuring-routers/rocketprism.md
      - guides/configuring-routers/omnitik.md
      - guides/configuring-routers/sxtsq.md
      - guides/configuring-routers/archer-a6.md
    - guides/installation/index.md
    - guides/ladder-safety.md
    - Realignment:
      - guides/realignment/index.md
      - guides/realignment/gather-materials.md
      - guides/realignment/check-los-software.md
      - guides/realignment/check-los-physical.md
      - Realign your LiteBeam:
        - guides/realignment/realign-litebeam.md
        - guides/realignment/realign-litebeam-uisp-app.md
    - guides/routeros-tips.md
    - UISP:
      - guides/uisp/setting-litebeam-passwords/index.md
    - Updating this documentation:
      - guides/updating-docs/index.md
      - guides/updating-docs/editing-docs.md
      - guides/updating-docs/adding-docs.md
      - guides/updating-docs/editing-menu.md
      - guides/updating-docs/faq.md
    - Infrastructure Admin:
      - guides/infrastructure-admin/add-wireguard-users.md
  - Hardware:
    - hardware/omnitik.md
    - hardware/liteap.md
    - hardware/litebeam.md
    - hardware/sxtsq.md
    - hardware/tp-link-ac1750.md
    - hardware/rocketprism.md
    - hardware/ccr2004.md
    - hardware/ccs610.md
  - Networking:
    - Supernodes:
      - networking/supernodes/index.md
      - networking/supernodes/bicas.md
      - networking/supernodes/tucson-house.md
    - Servers:
      - networking/servers/fw-mesh-host.md
      - networking/servers/fw-mesh-vm-nixos.md
    - networking/networking101.md
  - Services:
    - Mesh Services:
      - services/librenms.md
    - services/external.md
