site_name: Tucson Mesh Documentation 
theme:
  name: material
  features:
    - content.action.edit
  palette:
    primary: black
  logo: assets/logo.jpg
repo_url: https://github.com/tucsonmesh/tucsonmesh-docs
repo_name: tucsonmesh/tucsonmesh-docs 
edit_uri: edit/main/docs
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Guides:
    - guides/installation/index.md
    - guides/site-survey/index.md
    - Router Configuration:
      - guides/configuring-routers/index.md
      - guides/configuring-routers/litebeam.md
      - guides/configuring-routers/omnitik.md
      - guides/configuring-routers/sxtsq.md
      - guides/configuring-routers/archer-a6.md
    - guides/ladder-safety.md
    - guides/routeros-tips.md
    - Updating this documentation:
      - guides/updating-docs/index.md
      - guides/updating-docs/editing-docs.md
  - Hardware:
    - hardware/omnitik.md
    - hardware/liteap.md
    - hardware/litebeam.md
    - hardware/sxtsq.md
  - Networking:
    - Supernodes:
      - networking/supernodes/index.md
      - networking/supernodes/bicas.md
      - networking/supernodes/tucson-house.md
    - Servers:
      - networking/servers/fw-mesh-host.md
      - networking/servers/fw-mesh-vm-nixos.md
    - networking/networking101.md
  - Services:
    - Mesh Services:
      - services/librenms.md
